export const foods = [
    {
        id: 1,
        name: "Chicken Hell",
        imageUrl: "/FoodImage1.svg",
        deliveryTime: 30,
        rating: 4.5,
        type: "Healthy",
        price: 12.99,
    },
    {
        id: 2,
        name: "Spicy Tuna Roll",
        imageUrl: "/FoodImage2.png",
        deliveryTime: 25,
        rating: 4.7,
        type: "Trending",
        price: 15.99,
    },
    {
        id: 3,
        name: "Vegan Burger",
        imageUrl: "/FoodImage1.svg",
        deliveryTime: 20,
        rating: 4.8,
        type: "Supreme",
        price: 10.99,
    },
    {
        id: 4,
        name: "Margherita Pizza",
        imageUrl: "/FoodImage2.png",
        deliveryTime: 35,
        rating: 4.6,
        type: "Healthy",
        price: 14.99,
    },
    {
        id: 5,
        name: "Caesar Salad",
        imageUrl: "/FoodImage1.svg",
        deliveryTime: 15,
        rating: 4.4,
        type: "Trending",
        price: 9.99,
    },
    {
        id: 6,
        name: "BBQ Ribs",
        imageUrl: "/FoodImage2.png",
        deliveryTime: 40,
        rating: 4.9,
        type: "Healthy",
        price: 18.99,
    },
    {
        id: 7,
        name: "Pad Thai",
        imageUrl: "/FoodImage1.svg",
        deliveryTime: 30,
        rating: 4.5,
        type: "Supreme",
        price: 13.99,
    },
    {
        id: 8,
        name: "Cheeseburger",
        imageUrl: "/FoodImage2.png",
        deliveryTime: 25,
        rating: 4.7,
        type: "Trending",
        price: 11.99,
    }
]